
version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
